version: "3.7"
services:
  minio-init:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add local http://minio:9000 ${DRUPAL_DEFAULT_S3_ACCESS_KEY} ${DRUPAL_DEFAULT_S3_SECRET_KEY};
      /usr/bin/mc mb local/${DRUPAL_DEFAULT_S3_BUCKET};
      /usr/bin/mc policy set download local/${DRUPAL_DEFAULT_S3_BUCKET};
      exit 0;
      "
    networks:
      default:
        aliases:
          - localhost:minio
