version: "3.7"
services:
  drupal:
    depends_on:
    - snapshot
  mariadb:
    depends_on:
    - snapshot
  solr:
    depends_on:
    - snapshot
  snapshot:
    container_name: snapshot
    image: ${REPOSITORY}/snapshot:${SNAPSHOT_TAG}
    volumes:
    - drupal-sites-data:/data/drupal
    - mariadb-data:/data/mariadb-data
    - mariadb-files:/data/mariadb-files
    - solr-data:/data/solr
